version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000" 
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:11
    environment:
      - POSTGRES_DB=db1
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./../postgres_data:/var/lib/postgresql/data
